{
 "title": "ACA Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization_ratio",
     "legendFormat": "{{instance_id}}:{{name}}({{pid}})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_memory_utilization_ratio",
     "legendFormat": "{{instance_id}}:{{name}}({{pid}})"
    }
   ]
  },
  {
   "title": "Memory RSS Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes",
     "legendFormat": "{{instance_id}}:{{name}}({{pid}})"
    }
   ]
  }
 ]
}